Remove Dependency on Synsights
projectsyn/component-argocd pull request #13
Opened 2021-01-05 14:09 UTC by srueg

## Checklist

- [x] keep pull requests small so they can be easily reviewed
- [x] update ./CHANGELOG.md

2021-01-05 14:10 UTC, simu approved these changes

2021-01-05 16:10 UTC, corvus-ch requested changes
This component is missing documentation of the configuration parameters. Please add. At least document the parameters you added and create issue to document the rest.

2021-01-06 08:06 UTC, corvus-ch approved these changes

2021-01-06 08:06 UTC, corvus-ch commented on class/defaults.yml
> +      prometheus: platform
Not sure if adding _instance_ and or _name_ helps to grasp what this parameters is all about.

2021-01-06 09:40 UTC, merged