Upgrade to v2.2.1
projectsyn/component-argocd pull request #45
Opened 2021-12-29 15:42 UTC by bastjan

## Checklist

- [x] PR contains a single logical change (to build a better changelog).
- [ ] Update the documentation.
- [ ] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog.
- [ ] Link this PR to related issues or PRs.

2022-01-03 17:36 UTC, ccremer requested changes
This is a breaking change, but I'm missing the how-to page that describes how to upgrade this component. What are the options and upgrade steps users have that do that are using the bitnami image? Please add a page for good measure, even if it's just mentioning that quay.io image isn't supported anymore and any image pins in the hierararchy should be removed or ensured to use docker.io.

2022-01-03 17:36 UTC, ccremer commented on docs/modules/ROOT/pages/references/parameters.adoc
> +default:: `v2.2.2`
I don't think it's worth maintaining the version here also. (Especially if there might be Renovate support in the future)
```suggestion
default:: see `defaults.yaml`
```

2022-01-04 07:47 UTC, bastjan commented
> Please add a page for good measure, even if it's just mentioning that quay.io image isn't supported anymore and any image pins in the hierararchy should be removed or ensured to use docker.io.

Good point 👍

2022-01-04 08:19 UTC, simu approved these changes

2022-01-04 14:15 UTC, ccremer approved these changes

2022-01-05 07:36 UTC, merged